name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alaviss/setup-nim@master
        with:
          path: '../nim'
          version: 'version-1-4'
      - name : install htslib
        run: |
          sudo apt-get update
          sudo apt-get install git llvm curl wget libcurl4-openssl-dev autoconf
          wget https://github.com/samtools/htslib/archive/1.11.tar.gz
          tar xzf 1.11.tar.gz
          cd htslib-1.11/
          autoheader && autoconf && ./configure --disable-libcurl
          sudo make -j4 install
      - name: Run tests
        run: |
          export PATH=$HOME/.nimble/bin:$PATH
          export LD_LIBRARY_PATH=/usr/local/lib/
          nimble build -y
          nimble test

